shellEmulator: true

trustPolicy: no-downgrade

packages: []
catalog:
  husky: ^9.1.7
catalogs:
  build:
    '@nuxt/devtools': ^3.1.1
    '@nuxt/eslint': ^1.14.0
    '@nuxt/kit': ^4.3.1
    '@pinia/colada-nuxt': ^0.3.2
    '@pinia/nuxt': ^0.11.3
    '@rstore/nuxt-drizzle': ^0.8.3
    '@unocss/eslint-config': ^66.6.0
    '@unocss/nuxt': ^66.6.0
    nuxt: ^4.3.1
    unocss: ^66.6.0
    unplugin: ^3.0.0
    vite: ^7.3.1
  dev:
    '@antfu/eslint-config': ^7.3.0
    '@types/better-sqlite3': ^7.6.13
    '@types/node': ^25.2.2
    drizzle-kit: ^0.31.9
    eslint: ^9.39.2
    eslint-plugin-format: ^1.4.0
    eslint-plugin-oxlint: ^1.50.0
    oxlint: ^1.50.0
    typescript: ^5.9.3
    vue-tsc: ^3.2.4
  frontend:
    '@pinia/colada': ^0.21.6
    '@tanstack/query-db-collection': ^1.0.27
    '@tanstack/vue-db': ^0.0.107
    '@tanstack/vue-query': ^5.92.9
    better-sqlite3: ^12.6.2
    drizzle-orm: ^0.45.1
    pinia: ^3.0.4
    vue: ^3.5.27
    y-crossws: ^0.0.2
    y-indexeddb: ^9.0.12
    y-websocket: ^2.1.0
    yjs: ^13.6.24
  icons:
    '@iconify-json/carbon': ^1.2.18
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - unrs-resolver
